# Introduction of AllCCS {#intro}

AllCCS is a powerful platform to support various applications in Ion Mobility – Mass Spectrometry (IM-MS). It is designed to contain three major parts: 1) Unified CCS database, 2) Machine learning based CCS prediction, and 3) small molecule annotation. The unified CCS database is one of the most comprehensive CCS databases, covering ~1,700,000 small molecules. It provides a universal platform to contain both experimental CCS values (3,539) and predicted CCS values (over 10,000,000). Machine learning based CCS prediction function supports convenient prediction from SMILES structure to CCS values. This function utilizes the second generation CCS prediction algorithm to generate CCS values and RSS score for novel structures. Small molecule annotation provides an easy-to-use annotation function for various features or compounds. It is supported to search database with measured m/z and CCS for annotation, or in conjunct with any other annotation tools, such as MetFrag, CFM-ID, MS-Finder, and SIRUS etc.
