# CCS Database {#ccsdb}
<p style=text-align:justify>Unified CCS database aims to be a **unified platform** to host both literature-reported CCS values and in-silico predicted CCS values for ion mobility - mass spectrometry (IM-MS). It is **open-access** and **downloadable**. It contains **3,539 unified CCS values** which are summarized from **5,119 experimental CCS records**. These experimental CCS values are acquired with variable platform including DTIMS, TWIMS and TIMS etc., and have definitive confidence level. In addition, **~10,000,000 predicted CCS** values are provided for **~1,700,000** small molecules from multiple public database to support widespread applications, including metabolomics, lipidomics, drug screening, pesticide screening etc (Table \@ref(tab:dbinfo)). For each compound, its compound card contains meta information, complete records and links to other database. Finally, users can search interested compounds’ CCS values with the function of “Browser” and/or “Advance search” in this part.</p>

```{r dbinfo, tidy=FALSE, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
db_info <- readxl::read_xlsx('tables/database.xlsx')
db_info <- db_info %>% 
  dplyr::mutate(Database = paste0('[', Database, '](', Links, ')')) %>%
  dplyr::select(-Links)
knitr::kable(
  db_info, booktabs = TRUE,
  caption = 'A table of the first 10 rows of the mtcars data.'
)
```

## Compound Browser
Compound Browser Function provides a simple and straightforward way to browser the database. There are several browser conditions set in “Browser” part (Figure 2.1). 

- **Type**: It provides the choice of CCS values generated from experiments or prediction. 
-	**Database**: this option includes variable databases that cover all compounds in our unified database (Table \@ref(tab:dbinfo)). And users can choose specific database(s) for further execution. 
-	**Level**: it includes confidence level (ref section 2.2) of compounds in the unified database. It helps to choose compounds in the clearly defined level.

With browser conditions, users can screen out a series of interested compounds. Compounds entries would be displayed according to defined condition. In below text, it contains brief information for each compound. 

- **AllCCS ID**: As described in the section 1.2, users can click the link in the column of AllCCS ID to browse the corresponding compound card (Figure 1.2).
-	**Name**: compound name
- **Structure**: the image of compound structure
- **Formula**: chemical formula
- **Experimental CCS**: The unified CCS value reported in literature (See Ref 2.2.3)
- **Predicted CCS**: The predicted CCS values using machine-learning algorithm. (See Ref 2.2.4)
- **Highest level**: The highest confidence level of CCS values (See Ref 2.2.2)

Users can check the interested compounds in the last column. Click the download option, you could download a CSV table containing the information of you checked compounds (Figure 2.2). 

**Note**: 

- Download function supports up to **100** items for one time.



## Compound Card
In the compound card, it contains detail information of the compound. Next, we would like to explain each parts in the compound card.

### Compound information
It contains the basic information of the compound, including ALLCCS ID, name, formula, exact mass, SMILES, InChI, InChIKey, classification and structure in the right panel (Figure 2.3). Here, ClassyFire (http://classyfire.wishartlab.com) is used for compounds’ classification 【ref】.

### Unified CCS
This part contains the CCS information of different adduct forms with experimental CCS (if exists) and predicted CCS (Figure 2.4). The CCS reported here is the unified CCS values. We defined unified CCS as the average CCS value with definitive confidence level. The definition of confidence level can find in Table 2.2. CCS values of confidence 1, 2, 3 are all experimental values. The definition of confidence level: 

- **Confidence level 1** represents the CCS value of the specie which is acquired with DTIMS and has been reported at least twice in different labs with the maximum relative error less than 1%.
- **Confidence level 2** represents the CCS value of specie which is acquired with DTIMS, TWIMS or TIMS and has been reported at least twice in different labs with the maximum relative error less than 3%. 
- **Confidence level 3** represents the CCS value of specie is acquired with DTIMS, TWIMS or TIMS and only reported by one lab.
- **Confidence level 4** represents the predicted CCS value. 
- **Conflict** means the CCS value of specie which is acquired with DTIMS, TWIMS or TIMS and has been reported at least twice in different labs, but the maximum relative error is more than 3%.

### Experimental CCS records
This part records the detailed information of experimental CCS values (Figure 2.5). Compounds that have experimental CCS records contains the basic information of adduct form, m/z, experimental CCS values and charge. Besides, we also provide the information of used instrument platform and the type of ion mobility mass spectrometry. Detail information can be found in table 2.3. The measured approach is also provided, including single-field, multiple-fields, and empirical method. Corresponding reference literature is listed in the DOI column. If compounds don’t have experimental CCS record, it would have no information in this part.

### Predicted CCS records
This part records the detailed information of predicted CCS values (Figure 2.6). It provides the basic information of adduct forms, m/z, charge, corresponding predicted CCS values using AllCCS_V1 tool, users can reference our paper (XXXX) for details. Here we define representative structure similarity (RSS) to represent the similarity between this compound and the training set.

### Database link
This part provides the link to databases that contain the compound.

## Advanced Search
For advanced search, there are two modes for users to search the compounds in our unified CCS database, including **“single mode”** and **“batch mode”**.

### Single mode
As named, users can search for one compounds at one time in single mode. Here, we provide several optional identifiers for users to choose (Figure 2.8), including compound’s name, database ID, formula, SMILES, InChI, InChIKey. 

**Note**:

- If you don’t have confirmed identifier, keep it as null. 
- If there are contradictory identifier, it will return no available data.

### Batch mode
If there are multiple compounds, users can use batch mode to search. Currently, this function supports identifiers including “Database ID”, SMILES, InChIKey. While choosing database ID as identifier, there are several choice of databases in the right panel close to identifier option. 

**Note**: 

- In searching panel, you can enter one item per line.
- It should not contain extra space. 
- It supports up to 100 query items per request.
